### PR TITLE
Better labels for HitPolicy selector. All of them should have a good …

### PR DESCRIPTION
**Pull request by jomarko**
…short description too.

The hit policy selector is changed to contain explanation of hit policy and aggregator choices.

If user selected a hit policy, that doesn't use aggregator. the popover design is:
Screenshot_20230210_071145

If user selected the collect hit policy, the popover design is:
Screenshot_20230210_071202

### CODE REVIEW

**Comment by jomarko** [comment]
Trying to figure out proper description for rule order and output order hit policies.

**Comment by jomarko** [comment]
Pr is in draft state, waiting for approval of 'rule order' and 'output order' documentation https://github.com/kiegroup/kie-docs/pull/4464

**Comment by jomarko** [comment]
Aligned with approved changes from https://github.com/kiegroup/kie-docs/pull/4464 .

**Comment by jomarko** [comment]
@tiagobento it is ready for review

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
